name: "DEV DEPLOY"

on:
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: dev
      aws-assume-role-arn: "arn:aws:iam::308622697059:role/github-actions-fabriciosaand-pipeline"
      aws-region: "us-east-1"
      aws-statefile-s3-bucket: "fabriciosaand-sa-east-1-terraform-statefile"
      aws-lock-dynamodb-table: "fabriciosaand-sa-east-1-terraform-lock"
